replicaCount: 1

service:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP

istio:
  ingress:
    hosts:
      - prefix: '/test/'
        name: 'test-go-app'
        rewrite: '/'
        port: 80
