apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}
  namespace: backend
spec:
  hosts:
    - host162.net152.alania.net
  gateways:
    - backend-gateway
  http:
    - route:
        - destination:
            host: {{ .Release.Name }}.backend.svc.cluster.local
            port:
              number: 80